require("scrollbar").setup()
require('gitsigns').setup()
require('Comment').setup()
require('nvim-autopairs').setup()
require('spectre').setup()
require("trouble").setup()
require('spellsitter').setup()
